name 'rvm'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures rvm'
long_description 'Installs/Configures rvm'
version '0.1.3'
chef_version '>= 12.14' if respond_to?(:chef_version)
issues_url 'https://github.com/coquus-liber/rvm/issues'
source_url 'https://github.com/coquus-liber/rvm'
